"""Casi FINTI del banco delle decisioni (22.9.2026): divergenze fra i due
motori con la risposta giusta nota. Nessun dato clinico vero, nessun nome.
Formato: (famiglia, testo A = base, testo B = testimone, atteso) con atteso
«a», «b» oppure «incerto» (le due versioni sono entrambe plausibili e il
contesto non decide: un metodo ben tarato qui NON deve essere sicuro).
Si aggiungono ai 13 casi di banco-arbitro.py che arrivano all'arbitro."""

CASI_NUOVI = [
    # ── negazione: persa da un motore, coerente col contesto → la versione con la negazione
    ("negazione", "Il paziente è asintomatico. Riferisce dolore toracico da sforzo e la tolleranza è buona.",
     "Il paziente è asintomatico. Non riferisce dolore toracico da sforzo e la tolleranza è buona.", "b"),
    ("negazione", "All'ECG il ritmo è sinusale; non si osservano turbe della ripolarizzazione. Il quadro è rassicurante.",
     "All'ECG il ritmo è sinusale; si osservano turbe della ripolarizzazione. Il quadro è rassicurante.", "a"),
    ("negazione", "L'Holter delle 24 ore mostra episodi di fibrillazione atriale, per cui la terapia anticoagulante non è indicata.",
     "L'Holter delle 24 ore non mostra episodi di fibrillazione atriale, per cui la terapia anticoagulante non è indicata.", "b"),
    ("negazione", "La prova da sforzo è negativa per ischemia inducibile e il paziente non presenta sintomi durante il test.",
     "La prova da sforzo è negativa per ischemia inducibile e il paziente presenta sintomi durante il test.", "a"),
    ("negazione", "Il paziente è in buon compenso: presenta edemi declivi e riferisce ortopnea. Proseguiamo senza modifiche.",
     "Il paziente è in buon compenso: non presenta edemi declivi e non riferisce ortopnea. Proseguiamo senza modifiche.", "b"),
    ("negazione", "La coronarografia ha escluso stenosi significative; si conferma l'indicazione alla rivascolarizzazione.",
     "La coronarografia ha escluso stenosi significative; non si conferma l'indicazione alla rivascolarizzazione.", "b"),
    ("negazione", "Nega palpitazioni e sincopi. Il quadro aritmico è quindi tranquillo.",
     "Nega palpitazioni e sincopi. Il quadro aritmico non è quindi tranquillo.", "a"),
    ("negazione", "Dopo la sospensione del betabloccante la frequenza è salita e il paziente tollera bene la variazione.",
     "Dopo la sospensione del betabloccante la frequenza è salita e il paziente non tollera bene la variazione.", "incerto"),
    # ── qualificatori
    ("qualificatore", "Si osserva un'insufficienza aortica senza ripercussioni emodinamiche, da rivalutare fra due anni.",
     "Si osserva un'insufficienza aortica lieve senza ripercussioni emodinamiche, da rivalutare fra due anni.", "b"),
    ("qualificatore", "La stenosi aortica è ormai severa con sintomi da sforzo: discuto l'indicazione alla sostituzione valvolare.",
     "La stenosi aortica è ormai lieve con sintomi da sforzo: discuto l'indicazione alla sostituzione valvolare.", "a"),
    ("qualificatore", "La funzione sistolica ventricolare sinistra è conservata, con frazione d'eiezione nella norma.",
     "La funzione sistolica ventricolare sinistra è ridotta, con frazione d'eiezione nella norma.", "a"),
    ("qualificatore", "Il ventricolo sinistro è di dimensioni normali con lieve ipertrofia concentrica.",
     "Il ventricolo sinistro è di dimensioni normali con ipertrofia concentrica.", "a"),
    ("qualificatore", "L'insufficienza mitralica appare moderata, sovrapponibile al controllo precedente.",
     "L'insufficienza mitralica appare lieve, sovrapponibile al controllo precedente.", "incerto"),
    ("qualificatore", "Si rileva una dilatazione dell'atrio sinistro, lieve, senza altri reperti di rilievo.",
     "Si rileva una dilatazione dell'atrio sinistro, severa, senza altri reperti di rilievo.", "a"),
    ("qualificatore", "Il versamento pericardico è minimo e non emodinamicamente significativo.",
     "Il versamento pericardico è massivo e non emodinamicamente significativo.", "a"),
    ("qualificatore", "I profili pressori a domicilio risultano aumentati; aumento quindi la dose dell'antipertensivo.",
     "I profili pressori a domicilio risultano diminuiti; aumento quindi la dose dell'antipertensivo.", "a"),
    ("qualificatore", "I profili pressori risultano bassi con capogiri al mattino; riduco il diuretico.",
     "I profili pressori risultano alti con capogiri al mattino; riduco il diuretico.", "a"),
    # ── lateralità
    ("lateralità", "Al doppler si osserva una placca della carotide interna sinistra; la destra è indenne.",
     "Al doppler si osserva una placca della carotide interna destra; la destra è indenne.", "a"),
    ("lateralità", "Lamenta claudicatio all'arto inferiore destro; al doppler occlusione della femorale superficiale destra.",
     "Lamenta claudicatio all'arto inferiore destro; al doppler occlusione della femorale superficiale sinistra.", "a"),
    ("lateralità", "Presenta un blocco di branca destra già noto, invariato rispetto al tracciato precedente.",
     "Presenta un blocco di branca sinistra già noto, invariato rispetto al tracciato precedente.", "incerto"),
    ("lateralità", "L'ecocardiogramma mostra un ventricolo destro dilatato con pressione polmonare aumentata, come atteso nell'ipertensione polmonare.",
     "L'ecocardiogramma mostra un ventricolo sinistro dilatato con pressione polmonare aumentata, come atteso nell'ipertensione polmonare.", "a"),
    # ── termini e storpiature d'ascolto
    ("termine", "Si osserva un'acinesia lieve del setto interventricolare.",
     "Si osserva un'ipocinesia lieve del setto interventricolare.", "b"),
    ("termine", "La coronarografia documenta una stenosi serrada dell'arteria coronaria destra.",
     "La coronarografia documenta una stenosi serrata dell'arteria coronaria destra.", "b"),
    ("termine", "Il paziente è portatore di pacemaker bicamerale impiantato per blocco atrioventricolare.",
     "Il paziente è portatore di pacemaker bicamerale impiantato per blocco atrio ventricolare.", "incerto"),
    ("termine", "All'ecocardiogramma si osserva una valvola aortica bicuspide con lieve stenosi.",
     "All'ecocardiogramma si osserva una valvola aortica bicuspida con lieve stenosi.", "a"),
    ("termine", "Riferisce episodi di cardiopalmo a insorgenza improvvisa.",
     "Riferisce episodi di cardiopalma a insorgenza improvvisa.", "a"),
    ("termine", "Il tracciato mostra extrasistoli ventricolari isolate e monomorfe.",
     "Il tracciato mostra extrasistoli ventricolari isolate e monomorfi.", "a"),
    ("termine", "Si pone indicazione ad ablazione transcatetere della fibrillazione atriale.",
     "Si pone indicazione ad ablazione trans catetere della fibrillazione atriale.", "incerto"),
    ("termine", "All'ecocolordoppler dei tronchi sovraortici non si osservano stenosi emodinamicamente significative.",
     "All'ecocolordoppler dei tronchi sopra aortici non si osservano stenosi emodinamicamente significative.", "a"),
    ("termine", "Il paziente è in classe funzionale NYHA seconda, stabile.",
     "Il paziente è in classe funzionale nia seconda, stabile.", "a"),
    ("termine", "La scintigrafia miocardica non evidenzia difetti di perfusione inducibili.",
     "La scintigrafia miocardica non evidenzia difetti di percussione inducibili.", "a"),
    ("termine", "Si segnala una lieve insufficienza tricuspidale con PAPs stimata nella norma.",
     "Si segnala una lieve insufficienza tricuspidalica con PAPs stimata nella norma.", "a"),
    ("termine", "Il paziente è stato sottoposto a PTCA con impianto di stent medicato sulla discendente anteriore.",
     "Il paziente è stato sottoposto a PTCA con impianto di stent medicato sulla discendente interiore.", "a"),
    ("termine", "Si evidenzia un'ipertrofia settale asimmetrica compatibile con cardiomiopatia ipertrofica.",
     "Si evidenzia un'ipertrofia settale simmetrica compatibile con cardiomiopatia ipertrofica.", "a"),
    ("termine", "Il ritmo di base è un flutter atriale a conduzione variabile.",
     "Il ritmo di base è un flatter atriale a conduzione variabile.", "a"),
    ("termine", "Si consiglia un monitoraggio pressorio delle ventiquattro ore.",
     "Si consiglia un monitoraggio pressorio delle ventiquattr'ore.", "incerto"),
    # ── farmaci
    ("farmaco", "Prosegue con Eliquis due volte al giorno, ben tollerato.",
     "Prosegue con Eliquid due volte al giorno, ben tollerato.", "a"),
    ("farmaco", "In terapia con Xarelto la sera durante il pasto.",
     "In terapia con Sarelto la sera durante il pasto.", "a"),
    ("farmaco", "Introduco Entresto a basso dosaggio con controllo della creatinina fra due settimane.",
     "Introduco Entresta a basso dosaggio con controllo della creatinina fra due settimane.", "a"),
    ("farmaco", "Sostituisco la furosemide con torasemide al mattino.",
     "Sostituisco la furosemide con toracemide al mattino.", "a"),
    ("farmaco", "Aggiungo Jardiance al mattino per lo scompenso a frazione ridotta.",
     "Aggiungo Giardians al mattino per lo scompenso a frazione ridotta.", "a"),
    ("farmaco", "Prosegue con bisoprololo e ramipril alle dosi abituali.",
     "Prosegue con bisoprolo e ramipril alle dosi abituali.", "a"),
    ("farmaco", "La statina viene sostituita con rosuvastatina per intolleranza muscolare.",
     "La statina viene sostituita con rosuvastatina per tolleranza muscolare.", "a"),
    ("farmaco", "Suggerisco di proseguire l'amiodarone ancora per tre mesi.",
     "Suggerisco di proseguire il dronedarone ancora per tre mesi.", "incerto"),
    # ── grammatica e forma
    ("grammatica", "Lo rivedrò al prossimo controllo con gli esami del sangue.",
     "Lo rivedrò al prossimo controllo con gli esami del sangue aggiornati.", "incerto"),
    ("grammatica", "La paziente si presenta in buone condizioni generali e riferisce di stare bene.",
     "La paziente si presenta in buone condizioni generali e riferisce di stare benne.", "a"),
    ("grammatica", "Gli esami ematochimici risultano nella norma.",
     "Gli esami ematochimici risultano nella normale.", "a"),
    ("grammatica", "A distanza di sei mesi dall'intervento il paziente è asintomatico.",
     "A distanza di sei mesi dall'intervento il paziente e asintomatico.", "a"),
    ("grammatica", "Caro collega, ti ringrazio per avermi inviato in visita il tuo paziente.",
     "Caro collega, ti ringrazio per avermi inviato in visita il suo paziente.", "a"),
    ("grammatica", "Ho quindi deciso di non modificare la terapia in atto.",
     "Ho quindi deciso di non modificare la terapia in atti.", "a"),
    # ── senso clinico: parola sbagliata ma italiana
    ("senso", "Il paziente riferisce dispnea per sforzi moderati, come salire due piani di scale.",
     "Il paziente riferisce dispnea per sforzi modesti, come salire due piani di scale.", "incerto"),
    ("senso", "La pressione arteriosa in ambulatorio è di centotrenta su ottanta, ben controllata.",
     "La pressione arteriosa in ambulatorio è di centotrenta su ottanta, mal controllata.", "a"),
    ("senso", "Il colesterolo LDL resta sopra il target nonostante la statina: aggiungo ezetimibe.",
     "Il colesterolo LDL resta sotto il target nonostante la statina: aggiungo ezetimibe.", "a"),
    ("senso", "Alla luce del quadro stabile, il prossimo controllo è previsto fra un anno.",
     "Alla luce del quadro instabile, il prossimo controllo è previsto fra un anno.", "a"),
    ("senso", "Per il peggioramento della dispnea anticipo il controllo ecocardiografico.",
     "Per il miglioramento della dispnea anticipo il controllo ecocardiografico.", "a"),
    ("senso", "Il paziente ha sospeso il fumo da due anni e pratica attività fisica regolare.",
     "Il paziente ha ripreso il fumo da due anni e pratica attività fisica regolare.", "incerto"),
]
